[meta]
title="Semantic Search with OpenAI Embedding Creation"
description="""\
    Generate embeddings and run semantic search in your database in SQL. \
    """
icon="chart-network"
tags=["starter", "openai", "vectordb", "genai"]
destinations=["spaces"]
