[meta]
title="Getting Started with Notebooks"
description="""\
    SingleStore Notebooks with an AI Copilot (SQrL) for data prototyping, \
    visualization and analysis. \
    """
icon="notes"
tags=["starter", "python", "sqrl"]
destinations=["spaces"]
