[meta]
title="SingleStoreDB Notebook Basics"
description="""\
    Foundational guide to notebooks with essential tips and tricks. \
    """
icon="notes"
tags=["starter", "python", "dataframes"]
destinations=["spaces"]
