[meta]
title="Resume Evaluator"
description="""\
    Resume Evaluator using vectors stored in SingleStore to find sutiable resume for your job description. \
    """
icon="arrows-spin"
tags=["stater", "vectordb", "genai", "openai"]
destinations=["spaces"]
