[meta]
title="Image Matching with SQL"
description="""\
    Facial recognition using dot_product function on vectors stored in SingleStoreDB. \
    """
icon="face-viewfinder"
tags=["starter", "vectordb", "genai", "facenet"]
destinations=["spaces"]
