[meta]
title="Hybrid Search"
description="""\
    Hybrid search combines keyword search with semantic search,
    aiming to provide more accurate results.
    """
tags=["starter", "openai", "genai", "vectordb"]
icon="vector-circle"
destinations=["spaces"]
